**Taller — Limpieza y Análisis de Datos con Pandas y NumPy**

Objetivo
Aplicar técnicas de limpieza, transformación y análisis de datos utilizando las librerías Pandas y NumPy a partir de una base de datos con inconsistencias similares a escenarios reales.

Parte 1 — Exploración de datos (Pandas)<br>
Actividades<br>
Cargar la base de datos<br>
Mostrar:<br>
•
Primeras filas<br>
•
Información general del dataset<br>
•
Resumen estadístico<br>

In [8]:
import pandas as pd
from google.colab import files
import io

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define the file path for the CSV in Google Drive
file_path_drive = '/content/drive/MyDrive/Colab Notebooks/Taller — Limpieza y Análisis de Datos con Pandas y NumPy/ventas_sucias_5000.csv'

# Read the CSV file into a DataFrame, overwriting any previous 'df' if it existed from file upload
df = pd.read_csv(file_path_drive)

#print("Please upload your CSV file:")
#uploaded = files.upload()

# Assuming only one file is uploaded and it's a CSV
#for fn in uploaded.keys():
#    print('User uploaded file "{name}" with length {length} bytes'.format(name=fn, length=len(uploaded[fn])))
#    df = pd.read_csv(io.StringIO(uploaded[fn].decode('utf-8')))

# Display the first 5 rows of the DataFrame
display(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,Perú,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   object
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   object
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

In [11]:
#df.describe()

# Conteo de datos faltantes por columna
print("--- CANTIDAD DE VALORES NULOS ---")
print(df.isnull().sum())

# Conteo de filas completamente idénticas
print("\n--- TOTAL DE FILAS DUPLICADAS ---")
print(df.duplicated().sum())

--- CANTIDAD DE VALORES NULOS ---
cliente         0
producto        0
precio         50
cantidad       50
pais            0
metodo_pago     0
fecha           0
dtype: int64

--- TOTAL DE FILAS DUPLICADAS ---
0

Debes responder:

¿Cuántas filas y columnas tiene la base de datos?<br>
Filas: 7 | Columnas: 5000<br>
¿Qué tipos de datos identificas?<br>
Datos flotantes "decimales" y objects "cadenas de texto"<br>
¿Encuentras columnas con problemas o inconsistencias?<br>
Encuentro nulos en la columna "precio" y "cantidad"

Parte 2 — Limpieza de datos (Pandas) <br>
Realiza las siguientes tareas: <br>
• Corregir tipos de datos incorrectos  <br>
• Identificar y manejar valores nulos  <br>
• Estandarizar columnas de texto:  <br>
• País  <br>
• Método de pago  <br>
• Revisar posibles valores atípicos (outliers)  <br>
• Corregir formatos de fecha si es necesario  <br>

In [12]:
print(df['producto'].unique())

['Monitor' 'Laptop' 'Celular' 'Mouse' 'Teclado']

In [13]:
for column in df.columns:
    print(f"--- Unique values for column: {column} ---")
    print(df[column].unique())
    print("\n")

--- Unique values for column: cliente ---
['Maria' 'Luisa' 'Carlos' 'Juan' 'Pedro' 'Ana']


--- Unique values for column: producto ---
['Monitor' 'Laptop' 'Celular' 'Mouse' 'Teclado']


--- Unique values for column: precio ---
[1326.   55. 1203. ... 1788. 1019. 1672.]


--- Unique values for column: cantidad ---
[nan '2' '9' '3' '6' '7' '1' '8' '5' '4' 'three']


--- Unique values for column: pais ---
['peru' 'chile' 'Colombia' 'Perú' 'COL' 'Chile' 'col']


--- Unique values for column: metodo_pago ---
['Efectivo' 'Tarjeta' 'TRANSFERENCIA' 'transferencia']


--- Unique values for column: fecha ---
['2024-01-01 00:00:00' '2024-01-01 01:00:00' '2024-01-01 02:00:00' ...
 '2024-07-27 04:00:00' '2024-07-27 05:00:00' '2024-07-27 06:00:00']

In [15]:
# Corregir columna 'cantidad': Reemplazar texto 'three' y convertir a numérico
df['cantidad'] = df['cantidad'].replace('three', 3) # Replace the string 'three' with the number 3
df['cantidad'] = pd.to_numeric(df['cantidad'], errors='coerce') # Convert to numeric, coercing errors to NaN

# Corregir columna 'fecha': Convertir a tipo datetime
df['fecha'] = pd.to_datetime(df['fecha'])

# Estandarizar columna 'pais': Convertir a minúsculas y luego capitalizar la primera letra
df['pais'] = df['pais'].str.lower().str.capitalize()

# Estandarizar columna 'metodo_pago': Convertir a minúsculas y luego capitalizar la primera letra
df['metodo_pago'] = df['metodo_pago'].str.lower().str.capitalize()

# Verificar los cambios con df.info() y los valores únicos de las columnas modificadas
print("\n--- Información del DataFrame después de la corrección de tipos y estandarización ---")
df.info()

print("\n--- Valores únicos de 'cantidad' después de la corrección ---")
print(df['cantidad'].unique())

print("\n--- Valores únicos de 'pais' después de la estandarización ---")
print(df['pais'].unique())

print("\n--- Valores únicos de 'metodo_pago' después de la estandarización ---")
print(df['metodo_pago'].unique())

# Mostrar las primeras filas para verificar los cambios
print("\n--- Primeras 5 filas del DataFrame después de la limpieza ---")
display(df.head())

--- Información del DataFrame después de la corrección de tipos y estandarización ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   float64
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 273.6+ KB

--- Valores únicos de 'cantidad' después de la corrección ---
[nan  2.  9.  3.  6.  7.  1.  8.  5.  4.]

--- Valores únicos de 'pais' después de la estandarización ---
['Peru' 'Chile' 'Colombia' 'Perú' 'Col']

--- Valores únicos de 'metodo_pago' después de la estandarización ---
['Efectivo' 'Tarjeta' 'Transferencia']

--- Primeras 5 filas del DataFrame después de la limpieza ---

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,NaN,Peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2.0,Chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9.0,Colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3.0,Perú,Transferencia,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6.0,Chile,Tarjeta,2024-01-01 04:00:00

In [24]:
# Rellenar valores nulos en 'precio' con la mediana
median_precio = df['precio'].median()
df['precio'].fillna(median_precio, inplace=True)

# Rellenar valores nulos en 'cantidad' con la mediana
# Aseguramos que la cantidad sea un entero si es apropiado para el contexto
median_cantidad = df['cantidad'].median()
df['cantidad'].fillna(median_cantidad, inplace=True)

# Convertir 'cantidad' a entero después de rellenar los nulos, si tiene sentido para el contexto (ej. no se venden 2.5 unidades)
df['cantidad'] = df['cantidad'].astype(int)

# Covertir 'Col' a Colombia
df['pais'] = df['pais'].replace('Col', 'Colombia')

# Verificar la ausencia de valores nulos
print("--- Conteo de datos faltantes después de rellenar ---")
print(df.isnull().sum())

# Mostrar las primeras filas para verificar los cambios
print("\n--- Primeras 5 filas del DataFrame después de rellenar nulos ---")
display(df.head())

--- Conteo de datos faltantes después de rellenar ---
cliente        0
producto       0
precio         0
cantidad       0
pais           0
metodo_pago    0
fecha          0
total          0
dtype: int64

--- Primeras 5 filas del DataFrame después de rellenar nulos ---

/tmp/ipykernel_34957/3987789888.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['precio'].fillna(median_precio, inplace=True)
/tmp/ipykernel_34957/3987789888.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cantidad'].fillna(median_cantidad, inplace=True)

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
0,Maria,Monitor,1326.0,5,Peru,Efectivo,2024-01-01 00:00:00,6630.0
1,Luisa,Laptop,55.0,2,Chile,Tarjeta,2024-01-01 01:00:00,110.0
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00,10827.0
3,Luisa,Monitor,1304.0,3,Perú,Transferencia,2024-01-01 03:00:00,3912.0
4,Luisa,Monitor,426.0,6,Chile,Tarjeta,2024-01-01 04:00:00,2556.0

Debes responder: <br>
¿Qué problemas encontraste? 50 Nulos en el precio y 50 nulos en la cantidad. Había errores en el precio, país, cantidad y fecha
. <br>
¿Cómo los solucionaste? Identifique la mediana para rellenar las casillas nulos
Se estandarizo los datos de precio, fecha, cantidad y país <br>
¿Eliminaste registros? ¿Por qué?  No, solo lo reemplace con la mediana <br>

Parte 3 — Análisis con Pandas
Actividades
• Crear una nueva columna llamada total:  df['total'] = df['precio'] * df['cantidad']
Obtener:  
• Total vendido  
• Promedio de ventas  
• Venta máxima  
• Venta mínima  
•  
Identificar:  
Los 5 productos con mayor valor vendido  
El país con más ventas

In [25]:
 df['total'] = df['precio'] * df['cantidad']
 display(df.head())
 total_vendido = df['total'].sum()
 print(f"Total vendido: ${total_vendido}")
 promedio_ventas = df['total'].mean()
 print(f"Promedio de ventas: ${promedio_ventas}")
 venta_maxima = df['total'].max()
 print(f"Venta máxima: ${venta_maxima}")
 venta_minima = df['total'].min()
 print(f"Venta mínima: ${venta_minima}")

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
0,Maria,Monitor,1326.0,5,Peru,Efectivo,2024-01-01 00:00:00,6630.0
1,Luisa,Laptop,55.0,2,Chile,Tarjeta,2024-01-01 01:00:00,110.0
2,Carlos,Monitor,1203.0,9,Colombia,Efectivo,2024-01-01 02:00:00,10827.0
3,Luisa,Monitor,1304.0,3,Perú,Transferencia,2024-01-01 03:00:00,3912.0
4,Luisa,Monitor,426.0,6,Chile,Tarjeta,2024-01-01 04:00:00,2556.0

Total vendido: $102041921.0
Promedio de ventas: $20408.3842
Venta máxima: $8999991.0
Venta mínima: $10.0

In [27]:
mayor_valorvendido = df.nlargest(5, 'total')
print("Los 5 productos con mayor valor vendido:")
display(mayor_valorvendido)
País_masventas = df['pais'].value_counts().idxmax()
print(f"\nEl país con más ventas: {País_masventas}")

Los 5 productos con mayor valor vendido:

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha,total
2077,Ana,Teclado,999999.0,9,Perú,Transferencia,2024-03-27 13:00:00,8999991.0
1195,Ana,Laptop,999999.0,8,Colombia,Tarjeta,2024-02-19 19:00:00,7999992.0
1885,Maria,Mouse,999999.0,7,Colombia,Transferencia,2024-03-19 13:00:00,6999993.0
2976,Carlos,Celular,999999.0,6,Chile,Tarjeta,2024-05-04 00:00:00,5999994.0
1225,Ana,Monitor,999999.0,5,Colombia,Transferencia,2024-02-21 01:00:00,4999995.0

El país con más ventas: Colombia

Parte 4 — Introducción a NumPy <br>
Actividades <br>
• Convertir columnas numéricas a un array de NumPy:  data = df[['precio',
'cantidad']].to_numpy() <br>
• Separar columnas utilizando indexación:  precios = data[:, 0]
cantidades = data[:, 1] <br>
• Aplicar vectorización para calcular ventas totales: totales = precios *
cantidades<br>

In [31]:
from numpy import array
data = df[['precio', 'cantidad']].to_numpy()
array_precios = data[:, 0]
array_cantidades = data[:, 1]
ventas_totales = array_precios * array_cantidades

print("Ventas totales por cada fila:")
print(ventas_totales)
#

Ventas totales por cada fila:
[ 6630.   110. 10827. ...  3552. 10928.   406.]

Parte 5 — Análisis con NumPy
Utilizando funciones de NumPy, calcular:
• Suma total de ventas  
• Promedio de ventas  
• Venta máxima  
• Cantidad de ventas superiores a 1000  
•  
Debes responder:
¿Qué ventajas observas al usar NumPy?  
¿Qué significa “vectorización”?  
¿Qué hace la expresión data[:, 0]?

In [33]:
total_ventas = ventas_totales.sum()
print(f"Suma total de ventas: ${total_ventas}")
promedio_ventas = ventas_totales.mean()
print(f"Promedio de ventas: ${promedio_ventas}")
venta_maxima = ventas_totales.max()
print(f"Venta máxima: ${venta_maxima}")
cantidad_ventas_superiores_1000 = (ventas_totales > 1000).sum()
print(f"Cantidad de ventas superiores a 1000: {cantidad_ventas_superiores_1000}")
#

Suma total de ventas: $102041921.0
Promedio de ventas: $20408.3842
Venta máxima: $8999991.0
Cantidad de ventas superiores a 1000: 4248

¿Qué ventajas observas al usar NumPy?  
Saca datos más rápido y pocas líneas de código
¿Qué significa “vectorización”?
se refiere al proceso de convertir operaciones que normalmente se realizan en elementos individuales de datos en operaciones que se pueden aplicar a matrices
¿Qué hace la expresión data[:, 0]?  
Para decir que quiero tomar de inicio a fin la primera columna de la matriz

Parte 6 — Interpretación de resultados
Analiza y responde:
¿Los resultados obtenidos tienen sentido?
Sí, los resultados sí tienen sentido porque al final los cálculos salieron correctamente y coinciden entre Pandas y NumPy. Se pudo calcular el total vendido, el promedio, la venta máxima y mínima sin problemas. Además, después de limpiar los datos, la información quedó mucho más organizada.  


¿Detectaste valores sospechosos?  
Sí, encontré un valor muy alto en la venta máxima, porque llegó casi a 9 millones y eso se ve raro comparado con las demás ventas. Puede ser un error en el precio o en la cantidad. También había problemas como países escritos de diferentes formas, valores nulos y un texto dentro de una columna numérica.


¿El promedio representa correctamente los datos?
No del todo, porque ese valor tan alto afecta bastante el promedio. Entonces el promedio puede dar una idea un poco equivocada de las ventas reales. Creo que sería mejor revisar también la mediana para tener una medida más equilibrada.
¿Qué decisiones tomarías si esta fuera información real de negocio?


Primero revisaría los datos sospechosos para confirmar que no sean errores. Después mejoraría el sistema para evitar datos mal escritos o incompletos. También analizaría cuáles productos y países venden más para enfocarme en esos mercados y aumentar las ventas. Además, haría reportes frecuentes para controlar mejor la información.